name: com.example.simple_app
description: A simple Flutter application with a login screen and a home screen. The app uses the Cubit pattern for state management.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true